"use client";
import { useState, useSyncExternalStore } from "react";
import { Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { studioSnapshot, subscribeStudio, parseStudio, studioKey } from "@/lib/studio-preferences";
export function StudioPreferences() {
  const raw = useSyncExternalStore(subscribeStudio, studioSnapshot, () => null), values = parseStudio(raw);
  const [message, setMessage] = useState("");
  return <form key={raw || "defaults"} className="space-y-5 border-y border-zinc-200 py-6" onSubmit={event => {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    try { localStorage.setItem(studioKey, JSON.stringify({ theme: form.get("theme"), accent: form.get("accent"), density: form.get("density"), reducedMotion: form.get("reducedMotion") === "on", showBanner: form.get("showBanner") === "on", autosave: form.get("autosave") === "on", photoDuration: Number(form.get("photoDuration")), transition: form.get("transition") })); window.dispatchEvent(new Event("edifycut-studio")); setMessage("Personnalisation enregistrée."); }
    catch { setMessage("Le navigateur refuse l'enregistrement des préférences."); }
  }}><h2 className="text-lg font-semibold">Personnalisation du studio</h2><fieldset><legend className="mb-3 text-sm font-medium">Couleur d&apos;accent</legend><div className="flex gap-5">{[{ value: "indigo", label: "Indigo", color: "#4f46e5" }, { value: "cyan", label: "Cyan", color: "#0e7490" }, { value: "rose", label: "Rose", color: "#be185d" }].map(item => <label key={item.value} className="flex min-h-14 min-w-11 cursor-pointer flex-col items-center gap-2 text-xs"><input type="radio" name="accent" value={item.value} defaultChecked={values.accent === item.value} style={{ background: item.color }} className="size-8 cursor-pointer appearance-none rounded-full border-4 border-white outline outline-1 outline-zinc-200 checked:outline-2 checked:outline-zinc-900 focus-visible:outline-2" />{item.label}</label>)}</div></fieldset><div className="grid gap-4 sm:grid-cols-2"><label className="field-label">Thème<select name="theme" defaultValue={values.theme} className="h-11 rounded-md border border-zinc-200 bg-white px-3"><option value="system">Système</option><option value="light">Clair</option><option value="dark">Sombre</option></select></label><label className="field-label">Densité<select name="density" defaultValue={values.density} className="h-11 rounded-md border border-zinc-200 bg-white px-3"><option value="comfortable">Confortable</option><option value="compact">Compacte</option></select></label><label className="field-label">Durée des photos (s)<input name="photoDuration" type="number" min="1" max="60" defaultValue={values.photoDuration} className="rounded-md border border-zinc-200 bg-white px-3" /></label><label className="field-label">Transition par défaut<select name="transition" defaultValue={values.transition} className="h-11 rounded-md border border-zinc-200 bg-white px-3"><option value="none">Coupe directe</option><option value="fade">Fondu enchaîné</option><option value="wipeleft">Balayage</option><option value="slideleft">Glissement</option></select></label></div>{[{ name: "reducedMotion", label: "Réduire les animations", checked: values.reducedMotion }, { name: "showBanner", label: "Afficher la bannière du studio", checked: values.showBanner }, { name: "autosave", label: "Sauvegarde automatique des réglages de projet", checked: values.autosave }].map(item => <label key={item.name} className="flex min-h-11 items-center gap-3 text-sm"><input name={item.name} type="checkbox" defaultChecked={item.checked} className="size-4 accent-indigo-600" />{item.label}</label>)}<Button type="submit"><Save size={17} />Enregistrer la personnalisation</Button>{message && <p role="status" className="text-sm text-zinc-600">{message}</p>}</form>;
}
