import { InfoPage } from "@/components/layout/InfoPage";
export const metadata = { title: "Centre d'aide" };
const answers = [
  ["Comment utiliser la timeline audio ?", "Dans Montage & fusion, importez un fichier audio puis glissez sa forme d'onde pour le placer dans le montage. Les poignées découpent la source ; le zoom et l'alignement facilitent les raccords. Scinder ici découpe la sélection à la tête de lecture. Sélection règle le volume, les bornes et les fondus ; Mixage règle le son des vidéos et chaque piste. La fin de l'export suit toujours la durée des images. Les zones audio au-delà de cette fin sont grisées et ne sont pas exportées."],
  ["Comment assembler photos et vidéos ?", "Les fichiers importés apparaissent dans la médiathèque. Glissez une vidéo ou une photo sur la piste Image, ou un fichier audio sur une piste Audio. Sur smartphone, le bouton + ajoute le média au montage. Les flèches déplacent le clip sélectionné. Ajustez les coupes, la durée des photos et les transitions, puis exportez un MP4. L'aperçu montre le montage ; le rendu final encode les transitions et les fondus audio."],
  ["La capture du direct continue-t-elle si je quitte la page ?", "Oui. Live Capture fonctionne côté serveur : changer de page ou fermer l'onglet ne met pas la capture en pause. Le serveur doit rester en marche, connecté à Internet, et la machine ne doit pas se mettre en veille. Un redémarrage interrompt la capture, mais les fragments déjà enregistrés restent disponibles pour une reprise ou un assemblage. Les limites restent de 6 heures et 4 Go par capture."],
  ["Comment reprendre un projet ?", "Mes vidéos & projets conserve uniquement les réglages sur cet appareil. Choisissez Reprendre puis resélectionnez les fichiers originaux avec les mêmes noms et caractéristiques. Les médias ne sont pas conservés et vos originaux ne sont jamais modifiés. Le bouton Enregistrer reste disponible si vous désactivez la sauvegarde automatique dans les préférences."],
  ["Comment enregistrer ma voix ?", "Dans Atelier audio, choisissez Enregistrer au microphone et autorisez l'accès. Vous pouvez mettre en pause, reprendre puis terminer la prise. Elle est convertie localement en M4A et peut être coupée ou exportée. L'enregistrement nécessite HTTPS ou localhost et reste limité à 30 minutes ou 128 Mo."],
  ["Comment créer un extrait ?", "Importez un MP4, MOV ou WebM puis définissez Commencer à et Terminer à avec les positions dans la vidéo (HH:MM:SS.cc). Vous pouvez déplacer les bornes sur la timeline ou utiliser Début ici et Fin ici. Pour retirer un passage intérieur, cliquez sur Couper ici au début du passage puis sur Terminer la coupe ici à sa fin. L'aperçu peut sauter les passages retirés."],
  ["Comment supprimer les blancs ?", "Détecter les silences analyse le volume sonore de l'extrait, sans IA ni transcription. Réglez le seuil, la durée minimale et la marge de parole. Les passages proposés apparaissent dans la timeline et la liste : écoutez-les, décochez ceux à conserver puis exportez. La même coupe s'applique à l'image et au son. Une musique de fond peut masquer un silence, et une voix faible peut nécessiter un seuil plus prudent."],
  ["Que fait l'optimisation automatique ?", "Elle détecte les pauses de plus de 1,5 seconde à un seuil de −40 dB, conserve 250 ms autour de la parole, active la compression et ajoute de courts fondus. Elle garde votre vitesse, vos réglages de couleur et vos coupes manuelles. L'export est limité à 720p sans agrandir une source plus petite. Les réglages restent modifiables et l'action peut être annulée."],
  ["Comment enregistrer une vidéo YouTube ?", "Collez le lien dans la section YouTube, analysez la vidéo et choisissez un format et une qualité. Le bouton d'enregistrement ouvre un sélecteur d'emplacement sur les navigateurs compatibles. Ailleurs, les réglages de téléchargement du navigateur déterminent le dossier. Une fois le fichier enregistré, son ouverture dans l'éditeur est facultative."],
  ["Pourquoi la progression repart-elle de zéro ?", "YouTube fournit souvent l'image et le son séparément. La barre suit chaque flux, puis l'enregistrement sur votre appareil. Pendant la fusion et la conversion, le temps restant n'est pas connu."],
  ["Pourquoi un export peut-il prendre du temps ?", "Le montage utilise la mémoire et le processeur de votre appareil. Pour une vidéo longue, une qualité plus basse et la fermeture des onglets inutilisés peuvent aider. Gardez l'onglet ouvert pendant le traitement."],
  ["Comment capturer un direct ?", "Connectez-vous puis ouvrez Live Capture avec le lien d'un direct YouTube en cours. Les fragments de 30 secondes sont enregistrés sur le serveur. Pause ferme le fragment actuel ; Continuer repart au point actuel du direct, sans récupérer la période en pause. Assembler met en pause et produit un MP4. Terminer arrête et assemble ; la fin du flux déclenche aussi l'assemblage. Le serveur doit rester allumé."],
  ["Comment traiter un fichier audio ?", "Ouvrez Atelier audio et importez votre fichier. Définissez le début et la fin, la vitesse, le volume, les fondus et la normalisation, puis exportez en MP3, M4A ou WAV. Le traitement reste dans le navigateur et ne modifie pas l'original. Les fichiers sont limités à 512 Mo et la mémoire disponible peut réduire cette limite."],
  ["Où sont mes vidéos ?", "Les montages locaux et leurs exports restent sur votre appareil. Une fermeture ou un rechargement de l'éditeur supprime le projet temporaire. Les captures de directs sont conservées séparément sur le serveur : téléchargez-les ou supprimez-les depuis Live Capture. Les captures inactives expirent après 24 heures, avec nettoyage au prochain accès au service."],
  ["Comment partager vers WhatsApp ?", "Après l'export, choisissez Partager puis l'application souhaitée dans le menu de votre téléphone. Si votre navigateur ne permet pas le partage de fichiers, téléchargez la vidéo puis envoyez-la depuis WhatsApp ou une autre application."],
  ["J'ai oublié mon mot de passe", "Cette installation locale ne dispose pas d'envoi d'e-mails de récupération. Un administrateur peut définir un nouveau mot de passe depuis la page Administration. Une fois connecté, changez-le depuis Mon compte."],
];
export default function HelpPage() {
  return <InfoPage title="Centre d'aide" description="Des réponses concrètes pour importer, monter et partager vos vidéos."><div className="divide-y divide-zinc-200">{answers.map(([question, answer]) => <details key={question} className="py-5"><summary className="cursor-pointer text-base font-medium">{question}</summary><p className="mt-4 text-sm">{answer}</p></details>)}</div></InfoPage>;
}
